version: '3.3'

services:
    nginx-php:
        build:
            context: ./nginx-php
        container_name: sf.nginx-php
        volumes:
            - './nginx-php/nginx.conf:/etc/nginx/conf.d/nginx.conf'
            - '..:/var/www/project'
        ports:
            - '80:80'
    db:
        image: 'mysql:5.7'
        container_name: sf.mysql
        environment:
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        ports:
            - '${DB_PORT}:3306'
#        volumes:
#            - 'db-volume:/var/lib/mysql'
#volumes:
#    db-volume:
#        external:
#            name: ${DB_VOLUME}
networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                -   subnet: 192.168.223.0/28

