FROM wyveo/nginx-php-fpm:php74
#ENV DEBIAN_FRONTEND noninteractive
WORKDIR /var/www/project
# Install basics
#RUN apt-get update
#RUN apt-get install -y software-properties-common && add-apt-repository ppa:ondrej/php && apt-get update
#RUN apt-get install -y php7 php7-xdebug
